version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mercado_db
    restart: always
    environment:
      MYSQL_DATABASE: mercado_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    container_name: mercado_backend
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=mercado_db
      - DB_USER=root
      - DB_PASSWORD=root
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: mercado_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
